### ISSUE TITLE
Cryptic error when running

### ISSUE THREAD

**Issue by Zakini** [jaredpalmer/backpack#107]
I've been getting a strange error multiple times (~100) when trying to run `backpack` in my project:
```
2018-01-25 14:51 node[5617] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

The server does start and responds to requests, but I can't shake the feeling that this will cause a problem further down the line.

For context, I'm running:
- backpack-core@0.5.0
- node v8.9.4
- npm 5.6.0
- OS X 10.13.2 (high sierra)

Possibly related to [this issue on nodejs/node](https://github.com/nodejs/node/issues/15683)?

**Comment by Zakini** [comment]
In addition, when I stop the server with `ctrl+c` I get:
```
/Users/me/repos/project/node_modules/duplexer/index.js:31
    writer.on("drain", function() {
           ^

TypeError: Cannot read property 'on' of undefined
    at duplex (/Users/me/repos/project/node_modules/duplexer/index.js:31:12)
    at Object.module.exports (/Users/me/repos/project/node_modules/stream-combiner/index.js:8:17)
    at childrenOfPid (/Users/me/repos/project/node_modules/ps-tree/index.js:50:6)
    at main (/Users/me/repos/project/node_modules/pstree.remy/lib/index.js:17:12)
    at kill (/Users/me/repos/project/node_modules/nodemon/lib/monitor/run.js:302:5)
    at Bus.onQuit (/Users/me/repos/project/node_modules/nodemon/lib/monitor/run.js:361:5)
    at emitNone (events.js:111:20)
    at Bus.emit (events.js:208:7)
    at process.<anonymous> (/Users/me/repos/project/node_modules/nodemon/lib/monitor/run.js:383:9)
    at Object.onceWrapper (events.js:313:30)
```
