### ISSUE TITLE
Backpack example "with-typescript" doesnt compile

### ISSUE THREAD

**Issue by Mark083** [jaredpalmer/backpack#109]
node -v => v8.9.4  
npm -v => 5.6.0  
  
After doing it:

```
mkdir test
cd test
git clone https://github.com/palmerhq/backpack.git
cd ./backpack/examples/with-typescript/
npm install
npm run dev
```

I receive it:

```
> backpack-examples-with-typescript@0.5.0 dev ~/test/backpack/examples/with-typescript
> backpack dev


[at-loader] Using typescript@2.7.1 from typescript and "tsconfig.json" from ~/test/backpack/examples/with-typescript/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors


 ERROR  Failed to compile with 1 errors                                 19:38:08

 error  

[at-loader] ./src/main.ts:33:35 
    TS2322: Type 'string | 3000' is not assignable to type 'number'.
  Type 'string' is not assignable to type 'number'.

module.js:540
    throw err;
    ^

Error: Cannot find module '~/test/backpack/examples/with-typescript/build/main.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by Mark083** [comment]
There is a bug on example as pointed by @[Jeffrey Westerkamp] on  [this answer](https://stackoverflow.com/a/48600351/9217154)  .    
He gave a solution there too.
