### ISSUE TITLE
v0.8.0 Incompatible

### ISSUE THREAD

**Issue by yoyo837** [jaredpalmer/backpack#142]
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/backpack-core/babel.js
    at createDescriptor (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/babel-loader/lib/index.js:3:103)
```

**Comment by jaredpalmer** [comment]
Yah looks like babel-7 betas were not upgraded. Try out 0.8.1. Sorry about that.

**Comment by yoyo837** [comment]
If I `import` or `require` a `json` file with `v0.8.1` build

```

Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"s...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"s...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/webpack/lib/NormalModule.js:445:32)
    at runLoaders (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/webpack/lib/NormalModule.js:327:12)
    at /Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/tanghui/git/ydmap/ydmap-ssr-portal/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by jaredpalmer** [comment]
Cutting now

**Comment by yoyo837** [comment]
Thanks for your great job.
